### ISSUE TITLE
Breaking changes to consider

### ISSUE THREAD

**Issue by knickish** [not-fl3/nanoserde#103]
There's a small breaking change coming up in `v0.2.0` to split the code up by feature, it might be a good time to consider other change that are breaking but desirable.

- Use `std::io::{Read, Write}` instead of `Vec` for in the [de]serialization traits
    - This would potentially improve performance a lot for when reading/writing using something that's not a `Vec`, but basically requires `ser_{bin/json/ron}` to return a result.
- Add a `derive` feature to split out the `nanoserde-derive` crate from the trait definition and basic types 
    - This would further improve compile times for users who only use basic types or define their own custom impls
- ~~Add an `alloc` feature that gates the impls for containers that require `alloc`, and allows for nanoserde to be used in more constrained environments~~
    - ~~This would require the previous change to use `std::io::{Read, Write}`, as `nanoserde` uses `Vec` in its public interface currently~~
    - This appears infeasible currently, `std::io::{Read, Write}` are not available as exports from `core` or `alloc` (and `nanoserde` currently doesn't compute the size required to serialize an object) so there's no good way to store serialized data https://github.com/rust-lang/rust/issues/48331
 - VarInt encoding for length of stored collections and/or uints of various sizes 
     - #97 
     - This would save space over the wire/on disk, at the cost of some branchiness in en/decoding + backcompat break

**Comment by lenscas** [comment]
> Add a no-alloc feature that drops the impls for containers that require alloc, and allows for nanoserde to be used in more constrained environments 

Features should be additive, not subtractive. Enabling a feature should only add implementations, not remove them.

**Comment by knickish** [comment]
>Features should be additive, not subtractive. Enabling a feature should only add implementations, not remove them.

@lenscas changed it to `Add an alloc feature that gates the impls for containers that require alloc, and allows for nanoserde to be used in more constrained environments `

**Comment by knickish** [comment]
After some consideration, I think that none of these changes are worth the churn they would cause. Splitting up the formats made sense for reducing compile times and had an easy migration path, but none of the rest of these seem like unmitigated wins.
