### ISSUE TITLE
Allow disabling support for unneeded serialization formats.

### ISSUE THREAD

**Issue by thomcc** [not-fl3/nanoserde#12]
`nanoserde` supports several formats: RON, JSON, TOML, and a bincode-like binary format. For some cases I could imagine using more than one of these, but many programs may just need one or two. Including all of them seems to slows down the build a bit.

I think they should be behind e.g. `feature = "json"`, `feature = "ron"`, `feature = "bin"` and `feature = "toml`" (which would extend to the proc macro crate of course). I don't have strong feelings about which are on or off by default. (I don't think I'm the best person to argue either way there. Leaving them all on by default avoids breaking changes, though...).

**Comment by thomcc** [comment]
actually it looks like TOML is partial or just planned. Still, this applies to the rest of them anyway.

**Comment by knickish** [comment]
#70 is up to potentially implement this, wanted to get feedback on whether it is worth a breaking change with a version bump.
