### ISSUE TITLE
New features: support for NewType structs, ser/de of standard lib types

### ISSUE THREAD

**Issue by vdagonneau** [not-fl3/nanoserde#17]
Hello,

I have been using your crate a little bit in the hope of replacing serde. It is working great so far however, I feel some little features are missing. I am interested in knowing whether you think they would be interesting to add or not. I am willing to submit PRs to implement the features if you are interested.

First one is the support for NewType structs, unless I am mistaken currently the derive macro panics when applied to a NewType structs, this example panics:

```rust
#[derive(SerBin)]
struct MyNewType(u64);
```
I am not very confident I can actually implement that part unless you can give me pointers on what would be required to make it work.

Second one, would be to add support for serialization/deserialization of more complex standard library types like `PathBuf`, `OsString` or `SocketAddr`. I am pretty sure I can implement that fairly quickly but I want to make sure that you would be interested in merging it.

Thank you for the work you have been doing with nanoserde.

**Comment by vdagonneau** [comment]
I'm sorry, I was actually wrong with the first point and NewType structs. My problem comes when I have static arrays as struct members. The smallest reproduction is this:

```rust
use nanoserde::SerBin;

#[derive(SerBin)]
struct S([u8; 4]);

fn main() {}
```

**Comment by knickish** [comment]
Support for non-slice arrays was added [here](https://github.com/not-fl3/nanoserde/commit/7b6b2a8054f0935314deffa591753b694e111d0e)
