### ISSUE TITLE
Skip field?

### ISSUE THREAD

**Issue by pplanel** [not-fl3/nanoserde#46]
How can I skip a field?

**Comment by not-fl3** [comment]
iirc the closest we have is a `default` tag: https://github.com/not-fl3/nanoserde/blob/master/tests/json.rs#L169

**Comment by pplanel** [comment]
I found the [skip](https://github.com/not-fl3/nanoserde/blob/699a12cccc10b77cbb646d76f7c8029f6e48cc7d/derive/src/serde_json.rs#L31) attribute, but it expects the field to be an Option. It works for me.
