### ISSUE TITLE
What license is this repo under?

### ISSUE THREAD

**Issue by gaolaowai** [not-fl3/nanoserde#49]
Hi there!

I'm wondering whether or not to use this in some software I'm writing, and taking licenses into consideration, I don't see anything for this project.

Could you add an MIT license? 😄 

Thanks!

**Comment by gaolaowai** [comment]
Ah schucks, I see cargo.toml lists this:

```yaml
name = "nanoserde"
version = "0.1.30"
authors = ["makepad <info@makepad.nl>", "Fedor <not.fl3@gmail.com>"]
license = "MIT OR Apache-2.0"
description = """
Fork of makepad-tinyserde without any external dependencies.
Supports json, binary and ron.
```

While maybe not absolutely necessary, would still be nice to have it listed on repo itself, as that would help future folks who pass by to take up more interest in this crate.

Thanks!

**Comment by not-fl3** [comment]
sure, feel free to make a PR! 

the repo is a fork of makepad's tinyserde that used to be MIT/Apache2
