### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by theduke** [not-fl3/nanoserde#5]
According to the feature matrix enums are not supported.

Does this extend to simple text enums, as in: 

```rust
enum E {
  A,
  B,
}
```

If so, is support planned?

**Comment by not-fl3** [comment]
Enums are not supported at the moment at all and are planned. 

To support enums some work in "parse.rs"  will be required to support parsing enums alongside structs. And uncomment/fix some code in serializers to properly support enums. 
PRs are welcome!

**Comment by not-fl3** [comment]
Some progress on enum support is on `de_json_enum` branch: 
https://github.com/not-fl3/nanoserde/blob/de_json_enum/tests/json.rs#L317

**Comment by not-fl3** [comment]
Was merged for json and bin.
Maybe json's enum representation will be changed in the future, so, but this is going to be another issue :)

**Comment by theduke** [comment]
Awesome.
