### ISSUE TITLE
Unexpected data after end of the struct

### ISSUE THREAD

**Issue by Eason0729** [not-fl3/nanoserde#51]
```
proc-macro derive panicked
message: Unexpected data after end of the struct rustc[Click](rust-analyzer-diagnostics-view:/diagnostic%20message?1#file...graph.rs)
```

Here is the code that cause macro panic.
```rust
#[derive(Clone, DeBin, SerBin)]
pub struct Graph<V, E>
where
    V: Ord,
{
    edges: Vec<Vec<Edge<E>>>,
    values: BTreeMap<V, usize>
}
```

I personally fork nanoserde and add impl for ``BTreeMap``, and I think the problem is not the impl.
After digging into code of parser, I found that maybe trait bound parsing,``where V: Ord``, is missing in ``derive/src/parser``

**Comment by not-fl3** [comment]
yes, I believe `where` is not supported
