### ISSUE TITLE
BTreeMap support

### ISSUE THREAD

**Issue by tafia** [not-fl3/nanoserde#7]
Thanks for the crate! 

Really nice.

I am missing BTreeMap support which I imiagine should be close to HashMap one's.
I hope I'll find some time to make a PR in the coming days. but in case, opening an issue in case someone is interested in doing it first.

**Comment by not-fl3** [comment]
I think BTreeMap is support is a bit similar to this PR: https://github.com/not-fl3/nanoserde/pull/6

And I would prefer to add some "proxy" types on fields like this https://gist.github.com/not-fl3/f40d2025542ef9a4b8c76896343171dc instead of adding all possible containers into the library

**Comment by not-fl3** [comment]
Fill free to reopen if the proxy did not worked for your case!

**Comment by tafia** [comment]
I see. That's not very convenient but I'll give it a try.
