### ISSUE TITLE
clippy::ignored-unit-patterns on `DeJson`

### ISSUE THREAD

**Issue by frederikhors** [not-fl3/nanoserde#85]
With Rust 1.73 and `clippy::pedantic` I'm getting this warning:

```
matching over `()` is more explicit

for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ignored_unit_patterns

`-W clippy::ignored-unit-patterns` implied by `-W clippy::pedantic`clippy

nanoserde_derive
proc_macro DeJson
```

Why?

**Comment by knickish** [comment]
We haven't used clippy with nanoserde so far. If you post a repro I will at least add an ignore to the generated code, which should quiet that.

**Comment by frederikhors** [comment]
I think they fixed this with: https://github.com/rust-lang/rust-clippy/issues/11601.

But the warning for DeJson remains.

For the repro: I'm only using this code:

```rust
use nanoserde::DeJson;
use std::fmt;

#[derive(DeJson, Clone, Debug)]
pub struct Player {
    id: String,
    team: Team,
}
```

No more.
