### ISSUE TITLE
JSONC (JSON with comments) support

### ISSUE THREAD

**Issue by wait-what** [not-fl3/nanoserde#94]
It would be great if this was implemented. All that really needs to be done is that comments (`//` and `/* */`) should be ignored.

https://github.com/stephenberry/JSONC

I may try to implement this myself an open a PR. Would something like that be accepted?

**Comment by knickish** [comment]
Ignoring comments in JSON would probably be accepted, yes. I'll have a think about it and poke fedor if you make such a PR, but I'm not coming up with any real reason not to.
